package com.foodfindr.foodfindr.com.foodfindr.foodfindr.model;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

import java.util.List;

/**
 * Created by nites on 12/19/2015.
 */
@DynamoDBTable(tableName="Bill_Details")
public class BillDetails {
    private String ID;

    private Long userID;

    private String billID;

    private List<String> foodItem;

    private List<Integer> foodSentiment;

    @DynamoDBHashKey(attributeName = "ID")
    @DynamoDBAutoGeneratedKey
    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    @DynamoDBAttribute(attributeName = "User_ID")
    public Long getUserID() {
        return userID;
    }

    public void setUserID(Long userID) {
        this.userID = userID;
    }

    @DynamoDBAttribute(attributeName = "Bill_ID")
    public String getBillID() {
        return billID;
    }

    public void setBillID(String billID) {
        this.billID = billID;
    }

    @DynamoDBAttribute(attributeName = "Food_Item")
    public List<String> getFoodItem() {
        return foodItem;
    }

    public void setFoodItem(List<String> foodItem) {
        this.foodItem = foodItem;
    }

    @DynamoDBAttribute(attributeName = "Food_Sentiment")
    public List<Integer> getFoodSentiment() {
        return foodSentiment;
    }

    public void setFoodSentiment(List<Integer> foodSentiment) {
        this.foodSentiment = foodSentiment;
    }

    @Override
    public String toString() {
        return "BillDetails{" +
                "ID='" + ID + '\'' +
                ", userID=" + userID +
                ", billID='" + billID + '\'' +
                ", foodItem=" + foodItem +
                ", foodSentiment=" + foodSentiment +
                '}';
    }
}
