package com.foodfindr.foodfindr.com.foodfindr.foodfindr.model;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

import java.util.ArrayList;
import java.util.List;


@DynamoDBTable(tableName="Restaurant_Data")
public class RestaurantData {

	private String ID;
	
	private String restaurantName;
	
	private String restaurantAddress;
	
	private String restaurantPhoneNumber;
	
	private List<String> menuItems;

	@DynamoDBHashKey(attributeName = "ID")
    @DynamoDBAutoGeneratedKey
	public String getID() {
		return ID;
	}

	public void setID(String iD) {
		ID = iD;
	}

	@DynamoDBAttribute(attributeName = "Restaurant_Name")
	public String getRestaurantName() {
		return restaurantName;
	}

	public void setRestaurantName(String restaurantName) {
		this.restaurantName = restaurantName;
	}

	@DynamoDBAttribute(attributeName = "Restaurant_Address")
	public String getRestaurantAddress() {
		return restaurantAddress;
	}

	public void setRestaurantAddress(String restaurantAddress) {
		this.restaurantAddress = restaurantAddress;
	}

	@DynamoDBAttribute(attributeName = "Restaurant_Phone")
	public String getRestaurantPhoneNumber() {
		return restaurantPhoneNumber;
	}

	public void setRestaurantPhoneNumber(String restaurantPhoneNumber) {
		this.restaurantPhoneNumber = restaurantPhoneNumber;
	}

	@DynamoDBAttribute(attributeName="Menu_Items")
	public List<String> getMenuItems() {
		if(menuItems == null){
			menuItems = new ArrayList<String>();
		}
		return menuItems;
	}

	public void setMenuItems(List<String> menuItems) {
		this.menuItems = menuItems;
	}
	
	

}
