package com.foodfindr.foodfindr.com.foodfindr.foodfindr.model;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by suhani on 12/20/15.
 */

@DynamoDBTable(tableName="User")
public class User {

    private Long ID;

    private String name;

    private String emailID;

    public User(Long ID, String name, String emailID) {
        this.ID = ID;
        this.name = name;
        this.emailID = emailID;
    }

    @DynamoDBHashKey(attributeName = "User_ID")
    public Long getID() {
        return ID;
    }

    public void setID(Long iD) {
        ID = iD;
    }

    @DynamoDBAttribute(attributeName = "Name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute(attributeName = "EMAIL_ID")
    public String getEmailID() {
        return emailID;
    }

    public void setEmailID(String emailID) {
        this.emailID = emailID;
    }



}
